### ISSUE TITLE
Generated diagram in HTML shows 'o' character incorrectly

### ISSUE THREAD

**Issue by fdebrabander** [ahupowerdns/hello-dns#8]
HTML at https://powerdns.org/hello-dns/ has a funky looking diagram (twice). The diagram generated for the encoding of the query 'www.ietf.org', interprets the 'o' in a special way.

![table-error](https://user-images.githubusercontent.com/564268/38135279-99bde2c2-3417-11e8-8273-402949722a8f.png)

**Comment by ahupowerdns** [comment]
fixed.. horribly. With a Cyrillic o.
